<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Presensi_model extends CI_Model
{

    public $table = 'presensi';
    public $id = 'id_presensi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // SELECT * FROM presensi ORDER BY id, order DESC
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // SELECT * FROM presensi WHERE id=$id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // SELECT * FROM presensi ORDER BY id, order DESC
    function total_rows($q = NULL) {
        $this->db->like('id_presensi', $q);
		$this->db->or_like('presensi', $q);
		$this->db->or_like('gapok', $q);
		$this->db->or_like('tukes', $q);
		$this->db->or_like('tutra', $q);
		$this->db->or_like('tupen', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pekerjaan', $q);
		$this->db->or_like('pekerjaan', $q);
		$this->db->or_like('gapok', $q);
		$this->db->or_like('tukes', $q);
		$this->db->or_like('tutra', $q);
		$this->db->or_like('tupen', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table);
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Presensi_model.php */
/* Location: ./application/models/Pekerjaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-02 11:43:24 */
/* http://harviacode.com */